#!/bin/bash
#PBS -P FFEG
#PBS -l select=1:ncpus=8:mem=32GB:ngpus=1
#PBS -l walltime=168:00:00

cd /project/FFEG/origin

module load python/3.6.5
module load cuda/10.0.130
module load openmpi-gcc/4.0.0-cuda10



while true
do
    python train_v3.py --img_folder ./image3 \
    --checkpoints_folder ./checkpoints3 \
    --loss_file ./loss3.txt \
    --error_file ./error3.txt \
    --log_file ./log3.txt
    
    sleep 10
done
