#!/bin/bash
#PBS -P FFEG
#PBS -l select=1:ncpus=8:mem=32GB:ngpus=1
#PBS -l walltime=48:00:00

cd /project/FFEG/origin

module load python/3.6.5
module load cuda/10.0.130
module load openmpi-gcc/4.0.0-cuda10

while true
do

    python finetune_vox.py --img_folder ./image9 \
    --checkpoints_folder ./temp_completed \
    --loss_file ./loss9.txt \
    --error_file ./error9.txt \
    --log_file ./log9.txt
    
    sleep 10
done
