#!/bin/bash
#PBS -P FFEG
#PBS -l select=1:ncpus=8:mem=32GB:ngpus=1
#PBS -l walltime=100:00:00

cd /project/FFEG/origin

module load python/3.6.5
module load cuda/10.0.130
module load openmpi-gcc/4.0.0-cuda10


while true
do
    python combine_train.py --img_folder ./image1 \
    --checkpoints_folder ./checkpoints1 \
    --loss_file ./loss1.txt \
    --error_file ./error1.txt \
    --log_file ./log1.txt \
    
    sleep 10
done
