#!/bin/bash
#PBS -P FFEG
#PBS -l select=1:ncpus=8:mem=32GB:ngpus=1
#PBS -l walltime=100:00:00

cd /project/FFEG/origin

module load python/3.6.5
module load cuda/10.0.130
module load openmpi-gcc/4.0.0-cuda10




while true
do
    python combine_train.py --img_folder ./image7 \
    --checkpoints_folder ./checkpoints7 \
    --loss_file ./loss7.txt \
    --error_file ./error7.txt \
    --log_file ./log7.txt > out7.txt

    sleep 10
done


