#!/bin/bash
#PBS -P FFEG
#PBS -l select=1:ncpus=8:mem=32GB:ngpus=1
#PBS -l walltime=100:00:00

cd /project/FFEG/origin

module load python/3.6.5
module load cuda/10.0.130
module load openmpi-gcc/4.0.0-cuda10




while true
do
    python train.py --img_folder ./image5 \
    --checkpoints_folder ./checkpoints5 \
    --loss_file ./loss5.txt \
    --error_file ./error5.txt \
    --log_file ./log5.txt > out5.txt

    sleep 10
done


